local BASE_ID = 0x470000

LOCATION_MAPPING = {
    --spring breeze
    [ BASE_ID + 0x100 ] = {"@Spring Breeze - Green Greens/GG Maxim Tomato/Maxim"},
    [ BASE_ID + 0x200 ] = {"@Spring Breeze - Green Greens/GG 1-Up/1-Up"},
    [ BASE_ID + 0 ] = {"@Spring Breeze - Green Greens/GG Boss/Whispy Woods"},
    [ BASE_ID + 0x201 ] = {"@Spring Breeze - Float Islands/FI: 1-Up/1-Up"},
    [ BASE_ID + 0x400 ] = {"@Spring Breeze - Float Islands/FI: Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 1 ] = {"@Spring Breeze - Float Islands/FI: Boss/Lololo+Lalala"},
    [ BASE_ID + 0x202 ] = {"@Spring Breeze - Bubbly Clouds/BC 1-Up/1-Up"},
    [ BASE_ID + 0x203 ] = {"@Spring Breeze - Bubbly Clouds/BC Moon 1-Up/1-Up (Secret)"},
    [ BASE_ID + 0x101 ] = {"@Spring Breeze - Bubbly Clouds/BC Maxim Tomato/Maxim"},
    [ BASE_ID + 2 ] = {"@Spring Breeze - Bubbly Clouds/BC Boss/Kracko"},
    [ BASE_ID + 3 ] = {"@Spring Breeze - Mt. Dedede/Mt. Dedede Boss/King Dedede", "@Spring Breeze - Mt. Dedede/King Dedede Defeated/Spring Breeze Clear"},

    ----dynablade
    [ BASE_ID + 11 ] = {"@DynaBlade Overworld/Vs Iron Mam/Defeated"},
    --peanut plains
    [ BASE_ID + 4 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Goal",
                       "@DynaBlade - Peanut Plains/Peanut Plains Goal/Goal"},
    [ BASE_ID + 0x204 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains 1-up 1",
                           "@DynaBlade - Peanut Plains/PP 1-Up (Bomb Block)/1-Up"},
    [ BASE_ID + 0x205 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains 1-up 2",
                           "@DynaBlade - Peanut Plains/PP 1-Up (In the Sky)/1-Up"},
    [ BASE_ID + 0x102 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Maxim Tomato (Sword Essence)",
                           "@DynaBlade - Peanut Plains/PP Maxim Tomato (Sword Essence)/Maxim Tomato"},
    [ BASE_ID + 0x103 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Maxim Tomato (In the Sky)",
                           "@DynaBlade - Peanut Plains/PP Maxim Tomato (In the Sky)/Maxim Tomato"},
    [ BASE_ID + 0x104 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Maxim Tomato (Mini-BosS)",
                           "@DynaBlade - Peanut Plains/PP Maxim Tomato (Mini-Boss)/Maxim Tomato"},
    [ BASE_ID + 0x401 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Invincibility Candy",
                           "@DynaBlade - Peanut Plains/PP Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 0x800 ] = {"@DynaBlade Overworld/Peanut Plains/Peanut Plains Sword",
                           "@DynaBlade - Peanut Plains/PP Sword Essence/Sword"},

    --mallow castle
    [ BASE_ID + 5 ] = {"@DynaBlade Overworld/Mallow Castle/Mallow Castle Goal",
                       "@DynaBlade - Mallow Castle/Mallow Castle Goal/Goal"},
    [ BASE_ID + 9 ] = {"@DynaBlade Overworld/Mallow Castle/Hidden Switch",
                       "@DynaBlade - Mallow Castle/MC Hidden Switch/Switch 1"},
    [ BASE_ID + 0x105 ] = {"@DynaBlade Overworld/Mallow Castle/Maxim Tomato",
                           "@DynaBlade - Mallow Castle/MC Maxim Tomato/Maxim"},
    [ BASE_ID + 0x801 ] = {"@DynaBlade Overworld/Mallow Castle/Wheel",
                           "@DynaBlade - Mallow Castle/MC Wheel Essence/Wheel"},
    [ BASE_ID + 0x206 ] = {"@DynaBlade Overworld/Mallow Castle/1-Up Inside Castle",
                           "@DynaBlade - Mallow Castle/MC Inside Castle 1-Up/1-Up"},
    [ BASE_ID + 0x207 ] = {"@DynaBlade Overworld/Mallow Castle/1-Up Outside Castle",
                           "@DynaBlade - Mallow Castle/MC Outside Castle 1-Up/1-Up"},
    [ BASE_ID + 0x208 ] = {"@DynaBlade Overworld/Mallow Castle/Destroyed Castle 1-Up (Demolished Left)",
                           "@DynaBlade - Mallow Castle/MC Destroyed Castle 1/1-Up (Left)"},
    [ BASE_ID + 0x209 ] = {"@DynaBlade Overworld/Mallow Castle/Destroyed Castle 1-Up (Demolished Middle)",
                           "@DynaBlade - Mallow Castle/MC Destroyed Castle 2/1-Up (Middle)"},
    [ BASE_ID + 0x20A ] = {"@DynaBlade Overworld/Mallow Castle/Destroyed Castle 1-Up (Demolished Right)",
                           "@DynaBlade - Mallow Castle/MC Destroyed Castle 3/1-Up (Right)"},

    --cocoa cave
    [ BASE_ID + 6 ] = {"@DynaBlade Overworld/Cocoa Cave/Cocoa Cave Goal",
                       "@DynaBlade - Cocoa Cave/Cocoa Cave Goal/Goal"},
    [ BASE_ID + 0x108 ] = {"@DynaBlade Overworld/Cocoa Cave/Cocoa Cave Maxim Tomato",
                           "@DynaBlade - Cocoa Cave/CC Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x20B ] = {"@DynaBlade Overworld/Cocoa Cave/Cocoa Cave 1-Up (Starblock)",
                           "@DynaBlade - Cocoa Cave/CC 1-Up (Starblock)/1-Up"},
    [ BASE_ID + 0x20C ] = {"@DynaBlade Overworld/Cocoa Cave/Cocoa Cave 1-Up (Fire Cave)",
                           "@DynaBlade - Cocoa Cave/CC 1-Up (Fire Cave)/1-Up"},

    --candy mountain
    [ BASE_ID + 7 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Goal",
                       "@DynaBlade - Candy Mountain/Candy Mountain Goal/Goal"},
    [ BASE_ID + 10 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Hidden Switch",
                        "@DynaBlade - Candy Mountain/CM Hidden Switch/Switch 2"},
    [ BASE_ID + 0x402 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Invincibility Candy",
                           "@DynaBlade - Candy Mountain/CM Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 0x80C ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Hammer",
                           "@DynaBlade - Candy Mountain/Top Route/CM Hammer Essence",
                           "@DynaBlade - Candy Mountain/CM Hammer Essence/Hammer"},
    [ BASE_ID + 0x80D ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Copy",
                           "@DynaBlade - Candy Mountain/CM Copy Essence/Copy"},
    [ BASE_ID + 0x109 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Maxim Tomato (Cannon Left)",
                           "@DynaBlade - Candy Mountain/Cannon/CM Left Maxim",
                           "@DynaBlade - Candy Mountain/CM Maxim Tomato 1/Maxim Tomato (Cannon Left)"},
    [ BASE_ID + 0x10A ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Maxim Tomato (Cannon Right)",
                           "@DynaBlade - Candy Mountain/Cannon/CM Right Maxim",
                           "@DynaBlade - Candy Mountain/CM Maxim Tomato 2/Maxim Tomato (Cannon Right)"},
    [ BASE_ID + 0x10B ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain Maxim Tomato (Boss)",
                          "@DynaBlade - Candy Mountain/CM Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x20D ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Upper_",
                           "@DynaBlade - Candy Mountain/Top Route/CM 1-Up (Upper)",
                           "@DynaBlade - Candy Mountain/CM 1-Up (Upper)/1-Up"},
    [ BASE_ID + 0x20E ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Fire 1, Left)",
                           "@DynaBlade - Candy Mountain/Bottom Route/CM Left 1-Up",
                           "@DynaBlade - Candy Mountain/CM 1-Up Trio 1/Left 1-Up"},
    [ BASE_ID + 0x20F ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Fire 2, Top)",
                           "@DynaBlade - Candy Mountain/Bottom Route/CM Top 1-Up",
                           "@DynaBlade - Candy Mountain/CM 1-Up Trio 2/Top 1-Up"},
    [ BASE_ID + 0x210 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Fire 3, Right)",
                           "@DynaBlade - Candy Mountain/Bottom Route/CM Right 1-Up",
                           "@DynaBlade - Candy Mountain/CM 1-Up Trio 3/Right 1-Up"},
    [ BASE_ID + 0x211 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Cannon)",
                           "@DynaBlade - Candy Mountain/CM 1-Up (Cannon)/1-Up",
                           "@DynaBlade - Candy Mountain/Cannon/Candy Mountain 1-Up 5"},
    [ BASE_ID + 0x212 ] = {"@DynaBlade Overworld/Candy Mountain/Candy Mountain 1-Up (Stonewall)",
                           "@DynaBlade - Candy Mountain/CM 1-Up (Stonewall)/1-Up"},

    --nest
    [ BASE_ID + 8 ] = {"@DynaBlade Overworld/DynaBlade - Nest/DynaBlade Fight",
                       "@DynaBlade Overworld/DynaBlade - Nest/DynaBlade Clear"},
    [ BASE_ID + 0x860 ] = {"@DynaBlade Overworld/DynaBlade - Nest/Cutter"},
    [ BASE_ID + 0x862 ] = {"@DynaBlade Overworld/DynaBlade - Nest/Fire"},
    [ BASE_ID + 0x861 ] = {"@DynaBlade Overworld/DynaBlade - Nest/Beam"},
    [ BASE_ID + 0x863 ] = {"@DynaBlade Overworld/DynaBlade - Nest/Sword"},

    --bonus 1
    [ BASE_ID + 0x106 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Left Maxim"},
    [ BASE_ID + 0x107 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Right Maxim"},
    [ BASE_ID + 0x802 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Beam"},
    [ BASE_ID + 0x803 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Fire"},
    [ BASE_ID + 0x804 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Mirror"},
    [ BASE_ID + 0x805 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Fighter"},
    [ BASE_ID + 0x806 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Cutter"},
    [ BASE_ID + 0x807 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Plasma"},
    [ BASE_ID + 0x808 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Ninja"},
    [ BASE_ID + 0x809 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Sword"},
    [ BASE_ID + 0x80A ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Bomb"},
    [ BASE_ID + 0x80B ] = {"@DynaBlade Overworld/DynaBlade - Bonus 1/Hammer"},

    --bonus 2
    [ BASE_ID + 0x10C ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Maxim Tomato"},
    [ BASE_ID + 0x80E ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Wheel"},
    [ BASE_ID + 0x80F ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Yo-Yo"},
    [ BASE_ID + 0x810 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Wing"},
    [ BASE_ID + 0x811 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Stone"},
    [ BASE_ID + 0x812 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Parasol"},
    [ BASE_ID + 0x813 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Jet"},
    [ BASE_ID + 0x814 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Ice"},
    [ BASE_ID + 0x815 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Suplex"},
    [ BASE_ID + 0x816 ] = {"@DynaBlade Overworld/DynaBlade - Bonus 2/Copy"},

    --gourmet race
    [ BASE_ID + 12 ] = {"@Game Select/Gourmet Race/Win Round 1"},
    [ BASE_ID + 13 ] = {"@Game Select/Gourmet Race/Win Round 2"},
    [ BASE_ID + 14 ] = {"@Game Select/Gourmet Race/Win Round 3",
                        "@Game Select/Gourmet Race/Gourmet Race Clear"},
    [ BASE_ID + 0x817 ] = {"@Game Select/Gourmet Race/Jet"},
    [ BASE_ID + 0x818 ] = {"@Game Select/Gourmet Race/Parasol"},
    [ BASE_ID + 0x819 ] = {"@Game Select/Gourmet Race/Ninja"},
    [ BASE_ID + 0x81A ] = {"@Game Select/Gourmet Race/Wing"},
    [ BASE_ID + 0x81B ] = {"@Game Select/Gourmet Race/Wheel"},

    --the arena

    [BASE_ID + 113] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 114] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 115] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 116] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 117] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 118] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 119] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 120] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 121] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 122] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 123] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 124] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 125] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 126] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 127] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 128] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 129] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 130] = {"@Game Select/The Arena/Straight Wins"},
    [BASE_ID + 131] = {"@Game Select/The Arena/Straight Wins",
                       "@Game Select/The Arena/The Arena Clear"},
    [BASE_ID + 0x154] = {"@Game Select/The Arena/Maxim Tomato"},
    [BASE_ID + 0x155] = {"@Game Select/The Arena/Maxim Tomato"},
    [BASE_ID + 0x156] = {"@Game Select/The Arena/Maxim Tomato"},
    [BASE_ID + 0x157] = {"@Game Select/The Arena/Maxim Tomato"},
    [BASE_ID + 0x158] = {"@Game Select/The Arena/Maxim Tomato"},

    ----revenge of meta knight
    --chapter 1
    [ BASE_ID + 79 ] = {"@Revenge of Meta Knight - Chapter 1/RoMK Chapter 1 Clear/Chapter 1 Clear"},

    --chapter 2
    [ BASE_ID + 80 ] = {"@Revenge of Meta Knight - Chapter 2/RoMK Chapter 2 Clear/Chapter 2 Clear"},
    [ BASE_ID + 0x12B ] = {"@Revenge of Meta Knight - Chapter 2/CH2 Maxim Tomato (Underwater)/Maxim Tomato"},
    [ BASE_ID + 0x12C ] = {"@Revenge of Meta Knight - Chapter 2/CH2 Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x839 ] = {"@Revenge of Meta Knight - Chapter 2/CH2 Parasol Essence/Parasol"},
    [ BASE_ID + 0x83A ] = {"@Revenge of Meta Knight - Chapter 2/CH2 Bomb Essence/Bomb"},
    [ BASE_ID + 0x83B ] = {"@Revenge of Meta Knight - Chapter 2/CH2 Wing Essence/Wing"},

    --chapter 3
    [ BASE_ID + 81 ] = {"@Revenge of Meta Knight - Chapter 3/RoMK Chapter 3 Clear/Chapter 3 Clear"},
    [ BASE_ID + 0x21D ] = {"@Revenge of Meta Knight - Chapter 3/CH3 1-Up (Hidden Room)/1-Up"},
    [ BASE_ID + 0x22F ] = {"@Revenge of Meta Knight - Chapter 3/CH3 1-Up (Stake)/1-Up"},
    [ BASE_ID + 0x232 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 1-Up (Wall)/1-Up"},
    [ BASE_ID + 0x12D ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Maxim Tomato (Stake)/Maxim"},
    [ BASE_ID + 0x83C ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Hidden Room Essence 1/Cutter"},
    [ BASE_ID + 0x83D ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Hidden Room Essence 2/Sword"},
    [ BASE_ID + 0x83E ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Hidden Room Essence 3/Fighter"},
    [ BASE_ID + 0x83F] = {"@Revenge of Meta Knight - Chapter 3/CH3 Mini-Boss Essence 1/Cutter"},
    [ BASE_ID + 0x840 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Mini-Boss Essence 2/Ice"},
    [ BASE_ID + 0x841 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Stake Essence 1/Mirror"},
    [ BASE_ID + 0x842 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Stake Essence 2/Parasol"},
    [ BASE_ID + 0x843 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Stake Essence 3/Ninja"},
    [ BASE_ID + 0x844 ] = {"@Revenge of Meta Knight - Chapter 3/CH3 Wheel Essence/Wheel"},

    --chapter 4
    [ BASE_ID + 82 ] = {"@Revenge of Meta Knight - Chapter 4/RoMK Chapter 4 Clear/Chapter 4 Clear"},
    [ BASE_ID + 0x403 ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 0x12E ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Maxim Tomato (Hidden)/Maxim Tomato"},
    [ BASE_ID + 0x12F ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x864 ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Star Block Essence/Sword"},
    [ BASE_ID + 0x845 ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Boss Essence 1/Fire"},
    [ BASE_ID + 0x846 ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Boss Essence 2/Yo-Yo"},
    [ BASE_ID + 0x847 ] = {"@Revenge of Meta Knight - Chapter 4/CH4 Boss Essence 3/Beam"},

    --chapter 5
    [ BASE_ID + 83 ] = {"@Revenge of Meta Knight - Chapter 5/RoMK Chapter 5 Clear/Chapter 5 Clear"},
    [ BASE_ID + 0x130 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Maxim Tomato (Mini-Boss)/Maxim Tomato"},
    [ BASE_ID + 0x132 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Maxim Tomato (Armory)/Maxim Tomato"},
    [ BASE_ID + 0x131 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x848 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Boss Essence 1/Sword"},
    [ BASE_ID + 0x849 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Boss Essence 2/Wing"},
    [ BASE_ID + 0x84A ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 1/Ice"},
    [ BASE_ID + 0x84B ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 2/Parasol"},
    [ BASE_ID + 0x84C ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 3/Beam"},
    [ BASE_ID + 0x84D ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 4/Hammer"},
    [ BASE_ID + 0x84E ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 5/Plasma"},
    [ BASE_ID + 0x84F ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 6/Cutter"},
    [ BASE_ID + 0x850 ] = {"@Revenge of Meta Knight - Chapter 5/CH5 Armory Essence 7/Mirror"},

    --chapter 6
    [ BASE_ID + 84 ] = {"@Revenge of Meta Knight - Chapter 6/RoMK Chapter 6 Clear/Chapter 6 Clear"},
    [ BASE_ID + 0x404 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Invincibility Candy/Invincibility Candy",
                           "@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room/Invincibility Candy"},
    [ BASE_ID + 0x21E ] = {"@Revenge of Meta Knight - Chapter 6/CH6 1-Up (Yo-Yo)/1-Up"},
    [ BASE_ID + 0x21F ] = {"@Revenge of Meta Knight - Chapter 6/CH6 1-Up (Stash)/1-Up"},
    [ BASE_ID + 0x134 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Maxim Tomato (Stash)/Maxim Tomato"},
    [ BASE_ID + 0x133 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Maxim Tomato (Secret)/Maxim Tomato",
                           "@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room/Maxim Tomato"},
    [ BASE_ID + 0x135 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x851 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room Essence 1/Parasol",
                           "@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room/Parasol"},
    [ BASE_ID + 0x852 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room Essence 2/Jet",
                           "@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room/Jet"},
    [ BASE_ID + 0x853 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room Essence 3/Wing",
                           "@Revenge of Meta Knight - Chapter 6/CH6 Cloud Room/Wing"},
    [ BASE_ID + 0x854 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Switch Maze Top Essence/Wing"},
    [ BASE_ID + 0x855 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Switch Maze Bottom Essence/Suplex"},
    [ BASE_ID + 0x856 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Elevator Essence/Yo-Yo"},
    [ BASE_ID + 0x857 ] = {"@Revenge of Meta Knight - Chapter 6/CH6 Boss Essence/Bomb"},

    --chapter 7
    [ BASE_ID + 85 ] = {"@Revenge of Meta Knight - Chapter 7/RoMK Chapter 7 Clear/Chapter 7 Clear",
                        "@Revenge of Meta Knight - Chapter 7/CH7 Escape/RoMK Clear"},
    [ BASE_ID + 0x136 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Maxim Tomato (Auto)/Maxim Tomato"},
    [ BASE_ID + 0x137 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Maxim Tomato (Elevator Left)/Maxim Tomato"},
    [ BASE_ID + 0x138 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Maxim Tomato (Elevator Right)/Maxim Tomato"},
    [ BASE_ID + 0x139 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Maxim Tomato (Boss)/Maxim Tomato"},
    [ BASE_ID + 0x858 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Starting Essence 1/Cutter"},
    [ BASE_ID + 0x859 ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Starting Essence 2/Parasol"},
    [ BASE_ID + 0x85A ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Starting Essence 3/Yo-Yo"},
    [ BASE_ID + 0x85B ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Starting Essence 4/Stone"},
    [ BASE_ID + 0x85C ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Starting Essence 5/Ninja"},
    [ BASE_ID + 0x85F ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Boss Essence 1/Cutter"},
    [ BASE_ID + 0x85E ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Boss Essence 2/Sleep"},
    [ BASE_ID + 0x85D ] = {"@Revenge of Meta Knight - Chapter 7/CH7 Boss Essence 3/Ninja"},

    ----the great cave offensive
    --sub-tree
    [ BASE_ID + 19 ] = {"@TGCO Sub-Tree Area 1/Treasure 1/Gold Medal"},
    [ BASE_ID + 20 ] = {"@TGCO Sub-Tree Area 1/Treasure 2/Gold Coin"},
    [ BASE_ID + 21 ] = {"@TGCO Sub-Tree Area 1/Treasure 3/Whip"},
    [ BASE_ID + 22 ] = {"@TGCO Sub-Tree Area 2/Treasure 4/Crystal Ball"},
    [ BASE_ID + 23 ] = {"@TGCO Sub-Tree Area 2/Treasure 5/Lucky Cat"},
    [ BASE_ID + 24 ] = {"@TGCO Sub-Tree Area 3/Treasure 6/Seiryu Sword"},
    [ BASE_ID + 25 ] = {"@TGCO Sub-Tree Area 3/Treasure 7/Screw Ball"},
    [ BASE_ID + 26 ] = {"@TGCO Sub-Tree Area 3/Treasure 8/Echigo Candy"},
    [ BASE_ID + 27 ] = {"@TGCO Sub-Tree Area 3/Treasure 9/Zebra Mask"},
    [ BASE_ID + 0x10D ] = {"@TGCO Sub-Tree Area 3/Maxim Tomato (Zebra Mask)/Maxim Tomato"},
    [ BASE_ID + 0x213 ] = {"@TGCO Sub-Tree Area 3/1-Up (Underwater)/1-Up"},
    [ BASE_ID + 28 ] = {"@TGCO Sub-Tree Area 4/Treasure 10/Star Stone"},
    [ BASE_ID + 29 ] = {"@TGCO Sub-Tree Area 4/Treasure 11/Beast's Fang"},
    [ BASE_ID + 30 ] = {"@TGCO Sub-Tree Area 5/Treasure 12/Bandana"},
    [ BASE_ID + 31 ] = {"@TGCO Sub-Tree Area 5/Treasure 13/Springtime"},
    [ BASE_ID + 0x214 ] = {"@TGCO Sub-Tree Area 5/Springtime 1-Up/1-Up"},
    [ BASE_ID + 0x81C ] = {"@TGCO Sub-Tree Boss/Left Essence/Jet"},
    [ BASE_ID + 0x81D ] = {"@TGCO Sub-Tree Boss/Middle Essence/Mirror"},
    [ BASE_ID + 0x81E ] = {"@TGCO Sub-Tree Boss/Right Essence/Sword"},
    [ BASE_ID + 0x10E ] = {"@TGCO Sub-Tree Boss/Maxim Tomato (Essence)/Maxim Tomato"},
    [ BASE_ID + 15 ] = {"@TGCO Sub-Tree Boss/Boss/Fatty Whale"},
    [ BASE_ID + 0x10F ] = {"@TGCO Sub-Tree Boss/Minecart/Maxim Tomato"},

    --crystal
    [ BASE_ID + 32 ] = {"@TGCO Crystal Starting Area/Treasure 14/Dime"},
    [ BASE_ID + 33 ] = {"@TGCO Crystal Starting Area/Treasure 15/Glass Slippers"},
    [ BASE_ID + 0x215 ] = {"@TGCO Crystal Starting Area/1-Up (Underwater)/1-Up"},
    [ BASE_ID + 34 ] = {"@TGCO Crystal Left Door Area/Treasure 16/Goblet"},
    [ BASE_ID + 35 ] = {"@TGCO Crystal Left Door Area/Treasure 17/Saucepan"},
    [ BASE_ID + 36 ] = {"@TGCO Crystal Left Door Area/Treasure 18/Brass Knuckle"},
    [ BASE_ID + 37 ] = {"@TGCO Crystal Left Door Area/Treasure 19/Amber Rose"},
    [ BASE_ID + 38 ] = {"@TGCO Crystal Left Door Area/Treasure 20/Fish Fossil"},
    [ BASE_ID + 39 ] = {"@TGCO Crystal Left Door Area/Treasure 21/Beast Fossil"},
    [ BASE_ID + 40 ] = {"@TGCO Crystal Left Door Area/Treasure 22/Nunchucks"},
    [ BASE_ID + 41 ] = {"@TGCO Crystal Middle Door Area/Treasure 23/Bucket"},
    [ BASE_ID + 42 ] = {"@TGCO Crystal Middle Door Area/Treasure 24/Summertime"},
    [ BASE_ID + 43 ] = {"@TGCO Crystal Middle Door Area/Treasure 25/100 Dollar Coin"},
    [ BASE_ID + 0x110 ] = {"@TGCO Crystal Middle Door Area/Maxim Tomato (Bomb Block)/Maxim Tomato"},
    [ BASE_ID + 0x111 ] = {"@TGCO Crystal Middle Door Area/Maxim Tomato (Spikes)/Maxim Tomato"},
    [ BASE_ID + 44 ] = {"@TGCO Crystal Right Door Area/Treasure 26/Ancient Gem"},
    [ BASE_ID + 45 ] = {"@TGCO Crystal Right Door Area/Treasure 27/Falcon Helmet"},
    [ BASE_ID + 46 ] = {"@TGCO Crystal Right Door Area/Treasure 28/Dud"},
    [ BASE_ID + 47 ] = {"@TGCO Crystal Right Door Area/Treasure 29/Truth Mirror"},
    [ BASE_ID + 0x112 ] = {"@TGCO Crystal Right Door Area/Maxim Tomato (Before Truth Mirror)/Maxim Tomato"},
    [ BASE_ID + 0x81F ] = {"@TGCO Crystal Boss/Left Essence/Fighter"},
    [ BASE_ID + 0x820 ] = {"@TGCO Crystal Boss/Middle Essence/Wing"},
    [ BASE_ID + 0x821 ] = {"@TGCO Crystal Boss/Right Essence/Jet"},
    [ BASE_ID + 0x113 ] = {"@TGCO Crystal Boss/Maxim Tomato (Essence)/Maxim Tomato"},
    [ BASE_ID + 0x114 ] = {"@TGCO Crystal Boss/Minecart/Maxim Tomato"},
    [ BASE_ID + 16 ] = {"@TGCO Crystal Boss/Boss/Computer Virus"},

    --old tower
    [ BASE_ID + 49 ] = {"@TGCO Old Tower Area 1/Basement/Turtle Shell", "@TGCO Old Tower Area 2/Treasure 31/Turtle Shell"},
    [ BASE_ID + 50 ] = {"@TGCO Old Tower Area 1/Basement/Falchion", "@TGCO Old Tower Area 2/Treasure 32/Falchion"},
    [ BASE_ID + 51 ] = {"@TGCO Old Tower Area 1/Basement/Warrior Shield", "@TGCO Old Tower Area 2/Treasure 33/Warrior Shield"},
    [ BASE_ID + 0x11F ] = {"@TGCO Old Tower Area 1/Basement/Maxim Tomato (Mini-Boss)",
                           "@TGCO Old Tower Area 2/Mini-Boss Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x120 ] = {"@TGCO Old Tower Area 1/Basement/Maxim Tomato (Falchion Treasure)",
                           "@TGCO Old Tower Area 2/Maxim Tomato (Falchion Treasure)/Maxim Tomato"},
    [ BASE_ID + 0x217 ] = {"@TGCO Old Tower Area 1/Basement/1-Up (Falchion Treasure)",
                           "@TGCO Old Tower Area 2/1-Up (Falchion Treasure)/1-Up"},
    [ BASE_ID + 48 ] = {"@TGCO Old Tower Area 1/Treasure 30/Star Tiara"},
    [ BASE_ID + 0x116 ] = {"@TGCO Old Tower Area 1/Maxim Tomato (Bottom Entrance)/Maxim Tomato"},
    [ BASE_ID + 0x115 ] = {"@TGCO Old Tower Area 1/Minecart/Maxim Tomato"},
    [ BASE_ID + 0x216 ] = {"@TGCO Old Tower Area 1/1-Up (Bottom Entrance)/1-Up"},
    [ BASE_ID + 52 ] = {"@TGCO Old Tower Area 3/Treasure 34/Unicorn's Horn"},
    [ BASE_ID + 53 ] = {"@TGCO Old Tower Area 3/Treasure 35/Autumntime"},
    [ BASE_ID + 54 ] = {"@TGCO Old Tower Area 3/Treasure 36/Rice Bowl"},
    [ BASE_ID + 55 ] = {"@TGCO Old Tower Area 3/Treasure 37/Tut's Mask"},
    [ BASE_ID + 0x117 ] = {"@TGCO Old Tower Area 3/Maxim Tomato (Tut's Mask)/Maxim Tomato"},
    [ BASE_ID + 56 ] = {"@TGCO Old Tower Area 4/Treasure 38/Mr. Saturn"},
    [ BASE_ID + 57 ] = {"@TGCO Old Tower Area 4/Treasure 39/Armor"},
    [ BASE_ID + 58 ] = {"@TGCO Old Tower Area 4/Treasure 40/Treasure Box"},
    [ BASE_ID + 59 ] = {"@TGCO Old Tower Area 4/Treasure 41/Mannequin"},
    [ BASE_ID + 0x822 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 1/First Bottom"},
    [ BASE_ID + 0x823 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 2/Far Left"},
    [ BASE_ID + 0x824 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 3/Middle Top"},
    [ BASE_ID + 0x825 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 4/Second Middle"},
    [ BASE_ID + 0x826 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 5/First Top"},
    [ BASE_ID + 0x827 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 6/Second Bottom"},
    [ BASE_ID + 0x828 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 7/Far Top"},
    [ BASE_ID + 0x829 ] = {"@TGCO Old Tower Area 4/Sleep Room Essence 8/Far Bottom"},
    [ BASE_ID + 0x118 ] = {"@TGCO Old Tower Area 4/Maxim Tomato (Star Spring)/Maxim Tomato"},
    [ BASE_ID + 0x82A ] = {"@TGCO Old Tower Area 5/Left Essence/Ninja"},
    [ BASE_ID + 0x82B ] = {"@TGCO Old Tower Area 5/Middle Essence/Wing"},
    [ BASE_ID + 0x82C ] = {"@TGCO Old Tower Area 5/Right Essence/Plasma"},
    [ BASE_ID + 0x119 ] = {"@TGCO Old Tower Area 5/Maxim Tomato (Essence)/Maxim Tomato"},
    [ BASE_ID + 0x11A ] = {"@TGCO Old Tower Area 5/Boss Reward/Maxim Tomato"},
    [ BASE_ID + 17 ] = {"@TGCO Old Tower Area 5/Boss/Chameleo Arm"},
    [ BASE_ID + 60 ] = {"@TGCO Old Tower Area 6/Treasure 42/Gold Crown"},
    [ BASE_ID + 61 ] = {"@TGCO Old Tower Area 6/Treasure 43/King's Cape"},
    [ BASE_ID + 0x82D ] = {"@TGCO Old Tower Area 6/King's Cape Essence/Mirror"},
    [ BASE_ID + 62 ] = {"@TGCO Old Tower Area 7/Outside Left Spire/Model Ship",
                        "@TGCO Old Tower Area 7/Outside Right Spire/Model Ship",
                        "@TGCO Old Tower Area 7/Treasure 44/Model Ship"},
    [ BASE_ID + 0x11E ] = {"@TGCO Old Tower Area 7/Outside Left Spire/Maxim Tomato",
                           "@TGCO Old Tower Area 7/Maxim Tomato (Outside Left Spire)/Maxim Tomato"},
    [ BASE_ID + 0x11C ] = {"@TGCO Old Tower Area 7/Outside Right Spire/Maxim Tomato",
                           "@TGCO Old Tower Area 7/Maxim Tomato (Outside Right Spire)/Maxim Tomato"},
    [ BASE_ID + 63 ] = {"@TGCO Old Tower Area 7/Treasure 45/Sun Ring"},
    [ BASE_ID + 0x11D ] = {"@TGCO Old Tower Area 7/Maxim Tomato (Left Spire)/Maxim Tomato"},
    [ BASE_ID + 0x11B ] = {"@TGCO Old Tower Area 7/Maxim Tomato (Right Spire)/Maxim Tomato"},

    --garden
    [ BASE_ID + 64 ] = {"@TGCO Garden Starting Area/Treasure 46/Wintertime"},
    [ BASE_ID + 65 ] = {"@TGCO Garden Starting Area/Treasure 47/Katana"},
    [ BASE_ID + 0x121 ] = {"@TGCO Garden Starting Area/Maxim Tomato in the Wind/Maxim Tomato"},
    [ BASE_ID + 0x82E ] = {"@TGCO Garden Starting Area/Left Essence/Jet"},
    [ BASE_ID + 0x830 ] = {"@TGCO Garden Starting Area/Right Essence/Ninja"},
    [ BASE_ID + 0x82F ] = {"@TGCO Garden Starting Area/Middle Essence/Wing"},
    [ BASE_ID + 66 ] = {"@TGCO Garden Left Door Area/Treasure 48/Charm"},
    [ BASE_ID + 67 ] = {"@TGCO Garden Left Door Area/Treasure 49/Xmas Tree"},
    [ BASE_ID + 68 ] = {"@TGCO Garden Left Door Area/Cloud Area/Kong's Barrel",
                        "@TGCO Garden Cloud Area/Treasure 50/Kong's Barrel"},
    [ BASE_ID + 69 ] = {"@TGCO Garden Left Door Area/Cloud Area/Ramia's Scale",
                        "@TGCO Garden Cloud Area/Treasure 51/Ramia's Scale"},
    [ BASE_ID + 70 ] = {"@TGCO Garden Left Door Area/Cloud Area/Shiny Bamboo",
                        "@TGCO Garden Cloud Area/Treasure 52/Shiny Bamboo"},
    [ BASE_ID + 71 ] = {"@TGCO Garden Left Door Area/Cloud Area/Tire",
                        "@TGCO Garden Cloud Area/Treasure 53/Tire"},
    [ BASE_ID + 72 ] = {"@TGCO Garden Left Door Area/Cloud Area/Spirit Charm",
                        "@TGCO Garden Cloud Area/Treasure 54/Spirit Charm",
                        "@TGCO Garden Cloud Area/Starfall Room/Spirit Charm"},
    [ BASE_ID + 0x831 ] = {"@TGCO Garden Left Door Area/Cloud Area/Garden Wing (Cloud)",
                           "@TGCO Garden Cloud Area/Wing Essence/Wing"},
    [ BASE_ID + 0x832 ] = {"@TGCO Garden Left Door Area/Cloud Area/Garden Plasma",
                           "@TGCO Garden Cloud Area/Plasma Essence/Plasma"},
    [ BASE_ID + 0x834 ] = {"@TGCO Garden Left Door Area/Cloud Area/Garden Sleep",
                           "@TGCO Garden Cloud Area/Sleep Essence/Sleep"},
    [ BASE_ID + 0x835 ] = {"@TGCO Garden Left Door Area/Cloud Area/Garden Parasol (Cloud)",
                           "@TGCO Garden Cloud Area/Parasol Essence/Parasol"},
    [ BASE_ID + 0x21A ] = {"@TGCO Garden Left Door Area/Cloud Area/1-Up (Hidden Left)",
                           "@TGCO Garden Cloud Area/Hidden Room/1-Up (Hidden Left)",
                           "@TGCO Garden Cloud Area/1-Up (Hidden Left)/1-Up"},
    [ BASE_ID + 0x21B ] = {"@TGCO Garden Left Door Area/Cloud Area/1-Up (Hidden Right)",
                           "@TGCO Garden Cloud Area/Hidden Room/1-Up (Hidden Right)",
                           "@TGCO Garden Cloud Area/1-Up (Hidden Right)/1-Up"},
    [ BASE_ID + 0x127 ] = {"@TGCO Garden Left Door Area/Cloud Area/Maxim Tomato (Hidden)",
                           "@TGCO Garden Cloud Area/Hidden Room/Maxim Tomato (Hidden)",
                           "@TGCO Garden Cloud Area/Maxim Tomato (Hidden)/Maxim Tomato"},
    [ BASE_ID + 0x219 ] = {"@TGCO Garden Left Door Area/Cloud Area/1-Up (Starfall)",
                           "@TGCO Garden Cloud Area/Starfall Room/1-Up (Starfall)",
                           "@TGCO Garden Cloud Area/1-Up (Starfall)/1-Up"},
    [ BASE_ID + 0x126 ] = {"@TGCO Garden Left Door Area/Cloud Area/Maxim Tomato (Starfall)",
                           "@TGCO Garden Cloud Area/Starfall Room/Maxim Tomato (Starfall)",
                           "@TGCO Garden Cloud Area/Maxim Tomato (Starfall)/Maxim Tomato"},
    [ BASE_ID + 0x125 ] = {"@TGCO Garden Left Door Area/Cloud Area/Maxim Tomato (Starblock)",
                           "@TGCO Garden Cloud Area/Maxim Tomato (Starblock)/Maxim Tomato"},
    [ BASE_ID + 0x833 ] = {"@TGCO Garden Cloud Area/Wheel Essence/Wheel"},
    [ BASE_ID + 73 ] = {"@TGCO Garden Right Door Area/Treasure 55/Pegasus Wing"},
    [ BASE_ID + 74 ] = {"@TGCO Garden Right Door Area/Treasure 56/Raccoon Doll"},
    [ BASE_ID + 75 ] = {"@TGCO Garden Right Door Area/Treasure 57/Shell Whistle"},
    [ BASE_ID + 76 ] = {"@TGCO Garden Right Door Area/Treasure 58/Orichalcum"},
    [ BASE_ID + 0x122 ] = {"@TGCO Garden Right Door Area/Maxim Tomato (Cannon)/Maxim Tomato"},
    [ BASE_ID + 0x123 ] = {"@TGCO Garden Right Door Area/Maxim Tomato (Bugzzy)/Maxim Tomato"},
    [ BASE_ID + 0x124 ] = {"@TGCO Garden Right Door Area/Maxim Tomato (Underwater)/Maxim Tomato"},
    [ BASE_ID + 0x159 ] = {"@TGCO Garden Right Door Area/Maxim Tomato (Above Water)/Maxim Tomato"}
    [ BASE_ID + 0x230] = {"@TGCO Garden Right Door Area/1-Up (Gordo)/1-Up"},
    [ BASE_ID + 0x218 ] = {"@TGCO Garden Right Door Area/1-Up (Underwater)/1-Up"},
    [ BASE_ID + 77 ] = {"@TGCO Garden Center Door Area/Treasure 59/Platinum Ring"},
    [ BASE_ID + 78 ] = {"@TGCO Garden Center Door Area/Treasure 60/Triforce"},
    [ BASE_ID + 0x21C ] = {"@TGCO Garden Center Door Area/1-Up (Middle)/1-Up"},
    [ BASE_ID + 0x128 ] = {"@TGCO Garden Center Door Area/Maxim Tomato (Middle)/Maxim Tomato"},
    [ BASE_ID + 0x129 ] = {"@TGCO Garden Center Door Area/Maxim Tomato (Essence)/Maxim Tomato"},
    [ BASE_ID + 0x836 ] = {"@TGCO Garden Center Door Area/Left Essence/Bomb"},
    [ BASE_ID + 0x838 ] = {"@TGCO Garden Center Door Area/Right Essence/Parasol"},
    [ BASE_ID + 0x837 ] = {"@TGCO Garden Center Door Area/Middle Essence/Ice"},
    [ BASE_ID + 0x12A ] = {"@TGCO Garden Center Door Area/Minecart/Maxim Tomato"},
    --[ ??? ] = {"@TGCO Garden Center Door Area/Minecart/Escape"},
    [ BASE_ID + 18 ] = {"@TGCO Garden Center Door Area/Boss/Wham Bam Rock"},

    ----milky way wishes
    [ BASE_ID + 112 ] = {"@MWW Galaxy Map/???/Copy"},
    --[ ??? ] = {"@MWW Galaxy Map/Nova/Marx"},
    --floria
    [ BASE_ID + 88 ] = {"@MWW Floria/Cutter Essence/Cutter"},
    [ BASE_ID + 89 ] = {"@MWW Floria/Fighter Essence/Fighter"},
    [ BASE_ID + 90 ] = {"@MWW Floria/Ice Essence/Ice"},
    [ BASE_ID + 0x13A ] = {"@MWW Floria/Winter Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 87 ] = {"@MWW Floria/Boss/Twin Woods"},

    --aqualiss
    [ BASE_ID + 92 ] = {"@MWW Aqualiss/Beam Essence/Beam"},
    [ BASE_ID + 93 ] = {"@MWW Aqualiss/Parasol Essence/Parasol"},
    [ BASE_ID + 94 ] = {"@MWW Aqualiss/Sword Essence/Sword"},
    [ BASE_ID + 0x220 ] = {"@MWW Aqualiss/1-Up (Underwater)/1-Up"},
    [ BASE_ID + 0x221 ] = {"@MWW Aqualiss/Cannon Room 1-Up/1-Up"},
    [ BASE_ID + 0x222 ] = {"@MWW Aqualiss/Maze Room 1-Up/1-Up"},
    [ BASE_ID + 0x13B ] = {"@MWW Aqualiss/Maxim Tomato (Underwater)/Maxim Tomato"},
    [ BASE_ID + 0x13C ] = {"@MWW Aqualiss/Air Bubble Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x13D ] = {"@MWW Aqualiss/Sword Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x13E ] = {"@MWW Aqualiss/Maze Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 91 ] = {"@MWW Aqualiss/Boss/Fatty Whale"},

    --skyhigh
    [ BASE_ID + 96 ] = {"@MWW Skyhigh/Jet Essence/Jet"},
    [ BASE_ID + 97 ] = {"@MWW Skyhigh/Wheel Essence/Wheel"},
    [ BASE_ID + 98 ] = {"@MWW Skyhigh/Wing Essence/Wing"},
    [ BASE_ID + 0x223 ] = {"@MWW Skyhigh/1-Up (Open)/1-Up"},
    [ BASE_ID + 0x13F ] = {"@MWW Skyhigh/First Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x140 ] = {"@MWW Skyhigh/Door Maze Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x405 ] = {"@MWW Skyhigh/Door Maze Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 95 ] = {"@MWW Skyhigh/Boss/Kracko"},

    --hotbeat
    [ BASE_ID + 100 ] = {"@MWW Hotbeat/Fire Essence/Fire"},
    [ BASE_ID + 101 ] = {"@MWW Hotbeat/Suplex Essence/Suplex"},
    [ BASE_ID + 0x406 ] = {"@MWW Hotbeat/Fire Room Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 0x141 ] = {"@MWW Hotbeat/Minecart Room Maxim Tomato Below Bridge/Maxim Tomato"},
    [ BASE_ID + 0x142 ] = {"@MWW Hotbeat/Minecart Room Maxim Tomato With Food/Maxim Tomato"},
    [ BASE_ID + 0x143 ] = {"@MWW Hotbeat/Minecart Room Maxim Tomato Top Route/Maxim Tomato"},
    [ BASE_ID + 0x144 ] = {"@MWW Hotbeat/Cannon Room Maxim Tomato 1/Maxim Tomato"},
    [ BASE_ID + 0x146 ] = {"@MWW Hotbeat/Cannon Room Maxim Tomato 2/Maxim Tomato"},
    [ BASE_ID + 0x145 ] = {"@MWW Hotbeat/Cannon Room Maxim Tomato 3/Maxim Tomato"},
    [ BASE_ID + 0x147 ] = {"@MWW Hotbeat/Cannon Room Maxim Tomato 4/Maxim Tomato"},
    [ BASE_ID + 0x224 ] = {"@MWW Hotbeat/Minecart Room 1-Up/1-Up"},
    [ BASE_ID + 0x225 ] = {"@MWW Hotbeat/Cannon Room 1-Up 1/1-Up"},
    [ BASE_ID + 0x226 ] = {"@MWW Hotbeat/Cannon Room 1-Up 2/1-Up"},
    [ BASE_ID + 0x231 ] = {"@MWW Hotbeat/Cannon Room 1-Up 3/1-Up"},
    [ BASE_ID + 99 ] = {"@MWW Hotbeat/Boss/Chameleo Arm"},

    --cavios
    [ BASE_ID + 103 ] = {"@MWW Cavios/Bomb Essence/Bomb"},
    [ BASE_ID + 104 ] = {"@MWW Cavios/Hammer Essence/Hammer"},
    [ BASE_ID + 105 ] = {"@MWW Cavios/Stone Essence/Stone"},
    [ BASE_ID + 0x14C ] = {"@MWW Cavios/Stone Essence/Maxim Tomato"},
    [ BASE_ID + 0x228 ] = {"@MWW Cavios/Stone Essence/1-Up"},
    [ BASE_ID + 0x407 ] = {"@MWW Cavios/Stone Essence/Invincibility Candy"},
    [ BASE_ID + 0x148 ] = {"@MWW Cavios/Mini Boss Room Maxim Tomato 1/Maxim Tomato"},
    [ BASE_ID + 0x149 ] = {"@MWW Cavios/Mini Boss Room Maxim Tomato 2/Maxim Tomato"},
    [ BASE_ID + 0x14A ] = {"@MWW Cavios/Mini Boss Room Maxim Tomato 3/Maxim Tomato"},
    [ BASE_ID + 0x14B ] = {"@MWW Cavios/Blue Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x227 ] = {"@MWW Cavios/Mini Boss Room 1-Up/1-Up"},
    [ BASE_ID + 102 ] = {"@MWW Cavios/Boss/Wham Bam Rock"},

    --mecheye
    [ BASE_ID + 107 ] = {"@MWW Mecheye/Plasma Essence/Plasma"},
    [ BASE_ID + 108 ] = {"@MWW Mecheye/Yo-Yo Essence/Yo-Yo"},
    [ BASE_ID + 0x229 ] = {"@MWW Mecheye/1-Up (First Room)/1-Up"},
    [ BASE_ID + 0x22A ] = {"@MWW Mecheye/1-Up (Falling)/1-Up"},
    [ BASE_ID + 0x22B ] = {"@MWW Mecheye/1-Up (Plasma 1, Top)/1-Up"},
    [ BASE_ID + 0x22C ] = {"@MWW Mecheye/1-Up (Plasma 2, Middle)/1-Up"},
    [ BASE_ID + 0x22D ] = {"@MWW Mecheye/1-Up (Plasma 3, Bottom)/1-Up"},
    [ BASE_ID + 0x408 ] = {"@MWW Mecheye/Falling Invincibility Candy/Invincibility Candy"},
    [ BASE_ID + 0x14D ] = {"@MWW Mecheye/Maxim Tomato (Falling)/Maxim Tomato"},
    [ BASE_ID + 0x14E ] = {"@MWW Mecheye/Maxim Tomato (Mini-Boss Tower)/Maxim Tomato"},
    [ BASE_ID + 0x14F ] = {"@MWW Mecheye/Maxim Tomato (Plasma)/Maxim Tomato"},
    [ BASE_ID + 106 ] = {"@MWW Mecheye/Boss/Heavy Lobster"},

    --halfmoon
    [ BASE_ID + 110 ] = {"@MWW Halfmoon/Mirror Essence/Mirror"},
    [ BASE_ID + 111 ] = {"@MWW Halfmoon/Ninja Essence/Ninja"},
    [ BASE_ID + 0x22E ] = {"@MWW Halfmoon/1-Up (Warp Star)/1-Up"},
    [ BASE_ID + 0x150 ] = {"@MWW Halfmoon/Minecart Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x151 ] = {"@MWW Halfmoon/Warp Star Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x152 ] = {"@MWW Halfmoon/Windy Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 0x153 ] = {"@MWW Halfmoon/Boss Room Maxim Tomato/Maxim Tomato"},
    [ BASE_ID + 109 ] = {"@MWW Halfmoon/Boss/Computer Virus"},

}
